version: '2'
#define the services for the application
services:
  #define the service for NutriFHIR UI
  nutrifhir_ui:
    build:
      #specifiy the project build context
      context: .
      #specifiy the Dockerfile to use
      dockerfile: Dockerfile
    restart: always
    #bind host port 4200 to container port 4200
    ports:
       - 6001:6001